CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql
SET search_path = '';

CREATE TABLE IF NOT EXISTS alumni (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama VARCHAR(150) NOT NULL,
  angkatan VARCHAR(10) NOT NULL,
  tempat_lahir VARCHAR(100),
  tanggal_lahir DATE,
  gender VARCHAR(20) NOT NULL DEFAULT 'Laki-laki' CHECK (gender IN ('Laki-laki', 'Perempuan')),
  email VARCHAR(150) NOT NULL UNIQUE,
  phone VARCHAR(20) NOT NULL UNIQUE,
  profesi VARCHAR(100),
  punya_usaha SMALLINT NOT NULL DEFAULT 0,
  nama_usaha VARCHAR(150),
  kategori_usaha VARCHAR(100),
  provinsi VARCHAR(100),
  kota VARCHAR(100),
  alamat TEXT,
  is_verified SMALLINT NOT NULL DEFAULT 1,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usaha (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_usaha VARCHAR(150) NOT NULL,
  kategori VARCHAR(100) NOT NULL,
  phone_usaha VARCHAR(20),
  pemilik_id BIGINT NOT NULL REFERENCES alumni(id) ON DELETE CASCADE ON UPDATE CASCADE,
  is_verified SMALLINT NOT NULL DEFAULT 1,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_usaha_kategori ON usaha (kategori);

CREATE TABLE IF NOT EXISTS lapak_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS provinces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  token_hash CHAR(64) NOT NULL UNIQUE,
  user_agent VARCHAR(255),
  ip_address VARCHAR(45),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_session_admin_id ON admin_sessions (admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_session_expires ON admin_sessions (expires_at);

CREATE TABLE IF NOT EXISTS site_settings (
  id SMALLINT PRIMARY KEY,
  logo_text VARCHAR(120) NOT NULL DEFAULT 'IKA SMANDA',
  hide_logo_text_on_index SMALLINT NOT NULL DEFAULT 0,
  logo_image_url VARCHAR(255),
  favicon_url VARCHAR(255),
  whatsapp_number VARCHAR(30) NOT NULL DEFAULT '+62 812-3456-7890',
  hero_title VARCHAR(255) NOT NULL DEFAULT 'Ikatan Keluarga Alumni SMAN 2 Kendal',
  hero_subtitle TEXT,
  hero_primary_text VARCHAR(100) NOT NULL DEFAULT 'Daftar Sekarang',
  hero_primary_link VARCHAR(255) NOT NULL DEFAULT '/pendaftaran',
  hero_secondary_text VARCHAR(100) NOT NULL DEFAULT 'Lihat Direktori',
  hero_secondary_link VARCHAR(255) NOT NULL DEFAULT '/direktori',
  hero_background_url VARCHAR(255),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE alumni
  ADD COLUMN IF NOT EXISTS is_verified SMALLINT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ;

ALTER TABLE usaha
  ADD COLUMN IF NOT EXISTS phone_usaha VARCHAR(20),
  ADD COLUMN IF NOT EXISTS is_verified SMALLINT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ;

UPDATE usaha u
SET phone_usaha = a.phone
FROM alumni a
WHERE a.id = u.pemilik_id
  AND (u.phone_usaha IS NULL OR TRIM(u.phone_usaha) = '');

ALTER TABLE site_settings
  ADD COLUMN IF NOT EXISTS logo_image_url VARCHAR(255),
  ADD COLUMN IF NOT EXISTS hide_logo_text_on_index SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS whatsapp_number VARCHAR(30) NOT NULL DEFAULT '+62 812-3456-7890';

DROP TRIGGER IF EXISTS trg_lapak_categories_updated_at ON lapak_categories;
CREATE TRIGGER trg_lapak_categories_updated_at
BEFORE UPDATE ON lapak_categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_provinces_updated_at ON provinces;
CREATE TRIGGER trg_provinces_updated_at
BEFORE UPDATE ON provinces
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_admin_users_updated_at ON admin_users;
CREATE TRIGGER trg_admin_users_updated_at
BEFORE UPDATE ON admin_users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_site_settings_updated_at ON site_settings;
CREATE TRIGGER trg_site_settings_updated_at
BEFORE UPDATE ON site_settings
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

INSERT INTO site_settings (
  id,
  logo_text,
  whatsapp_number,
  hero_title,
  hero_subtitle,
  hero_primary_text,
  hero_primary_link,
  hero_secondary_text,
  hero_secondary_link
)
VALUES (
  1,
  'IKA SMANDA',
  '+62 812-3456-7890',
  'Ikatan Keluarga Alumni SMAN 2 Kendal',
  'Menghubungkan alumni lintas angkatan dan membangun kolaborasi nyata bagi almamater serta sesama alumni.',
  'Daftar Sekarang',
  '/pendaftaran',
  'Lihat Direktori',
  '/direktori'
)
ON CONFLICT (id) DO NOTHING;

UPDATE site_settings
SET
  whatsapp_number = COALESCE(NULLIF(TRIM(whatsapp_number), ''), '+62 812-3456-7890'),
  hero_primary_link = CASE
    WHEN hero_primary_link = '#daftar' THEN '/pendaftaran'
    ELSE hero_primary_link
  END,
  hero_secondary_link = CASE
    WHEN hero_secondary_link = '#direktori' THEN '/direktori'
    ELSE hero_secondary_link
  END
WHERE id = 1;

INSERT INTO lapak_categories (name)
VALUES
  ('Kuliner'),
  ('Jasa'),
  ('Fashion'),
  ('Teknologi')
ON CONFLICT (name) DO NOTHING;

INSERT INTO provinces (name)
VALUES
  ('Aceh'),
  ('Sumatera Utara'),
  ('Sumatera Barat'),
  ('Riau'),
  ('Kepulauan Riau'),
  ('Jambi'),
  ('Sumatera Selatan'),
  ('Kepulauan Bangka Belitung'),
  ('Bengkulu'),
  ('Lampung'),
  ('DKI Jakarta'),
  ('Jawa Barat'),
  ('Jawa Tengah'),
  ('DI Yogyakarta'),
  ('Jawa Timur'),
  ('Banten'),
  ('Bali'),
  ('Nusa Tenggara Barat'),
  ('Nusa Tenggara Timur'),
  ('Kalimantan Barat'),
  ('Kalimantan Tengah'),
  ('Kalimantan Selatan'),
  ('Kalimantan Timur'),
  ('Kalimantan Utara'),
  ('Sulawesi Utara'),
  ('Gorontalo'),
  ('Sulawesi Tengah'),
  ('Sulawesi Barat'),
  ('Sulawesi Selatan'),
  ('Sulawesi Tenggara'),
  ('Maluku'),
  ('Maluku Utara'),
  ('Papua'),
  ('Papua Barat'),
  ('Papua Barat Daya'),
  ('Papua Selatan'),
  ('Papua Tengah'),
  ('Papua Pegunungan')
ON CONFLICT (name) DO NOTHING;
